# Generated by Django 3.1.7 on 2021-03-16 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,20}$')])),
                ('surname', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,20}$')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('profession', models.CharField(max_length=30)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ('name', 'surname'),
                'db_table': 'employee',
            },
        ),
    ]
