# Generated by Django 3.1.7 on 2021-03-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companymodels_user'),
        ('employee', '0002_auto_20210317_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.companymodels'),
            preserve_default=False,
        ),
    ]
